### ISSUE TITLE
Noticed by HN

### ISSUE THREAD

**Issue by andrewducker** [FractalFir/rustc_codegen_clr#1]
Thought you might like to know that you made Hacker News:
https://news.ycombinator.com/item?id=37304167

(There wasn't an email address on your blog, so I figured this was the easiest way to get in touch.)

**Comment by FractalFir** [comment]
Thanks for letting me know! 
I am not exactly sure what this means, since I have not heard of hacker news before. It seems to me like a curated programming forum?
Nonetheless, it is really nice seeing the enthusiasm people have for my work!

**Comment by andrewducker** [comment]
Yeah, it's probably the largest tech forum off of Reddit.  Or at least it used to be.  I don't know if it's shrunk over the last few years.  Generally has pretty good quality of discussion.  Except when it really doesn't :-)
