### ISSUE TITLE
Test assemblies are invalid when loading with dotPeek

### ISSUE THREAD

**Issue by karashiiro** [FractalFir/rustc_codegen_clr#18]
The assembly output for `test_lib` tests seems to be invalid, and cannot be loaded with dotPeek to view their IL. The `run_test` executables seem to work fine.

As a comparison, this is what shows up when loading `add.exe`:
![image](https://github.com/FractalFir/rustc_codegen_clr/assets/49822414/f34f05c7-7d0f-4dae-add5-234c4d960e35)

And this is what shows up when loading `binops.dll`:
![image](https://github.com/FractalFir/rustc_codegen_clr/assets/49822414/7578ea4b-1798-4d9f-aa36-bc44f7c33e1a)

I think this has been happening ever since the linker changes about a week ago.

**Comment by FractalFir** [comment]
I think I caught the source of the bug:
the linker does not yet differentiate between static libraries and executables.

**Comment by FractalFir** [comment]
The `test_lib`s seem to not build at all, but the output of rustc is empty. The assembly that you can't open is likely an old one.

**Comment by FractalFir** [comment]
UPDATE: the issue with assemblies not being built is a separate one, and it got fixed. It seems like the codegen saves .rlib files as .dll

**Comment by FractalFir** [comment]
Fixed in `26f6a20b18f1f81a75db56383479429d78d8b0e7`.  The root cause of the bugs was .rlib files being saved as .dll, and the linker not being invoked by the test runner.

**Comment by karashiiro** [comment]
Confirmed working now, thanks!
