### ISSUE TITLE
Cross pollinate ideas

### ISSUE THREAD

**Issue by kant2002** [FractalFir/rustc_codegen_clr#2]
As on of the developer for C to .NET compiler https://github.com/fornever/cesium I notice that we can/have share potentially same issues when working on FFI with native world/existing libraries. So want to ley you know about our existence.

I think the only one most interesting thing for you, is how [we handle pointers](https://github.com/ForNeVeR/Cesium/issues/132). This is not rocket since obviously, but still open to learn something new from your project too.

Have a good day, and keep working on cool projects

**Comment by FractalFir** [comment]
Really nice project! 
I previously did not think about `size_of` being used this way. I will look forward to what kind of solution you come up with!
