### ISSUE TITLE
[MISCOMPILATION] file not found for module `utilis` in cilly

### ISSUE THREAD

**Issue by bingxinliu** [FractalFir/rustc_codegen_clr#48]
**Describe the bug**
`cilly` does not have `utilis` crate.
When compiling the package, rustc says:
```
error[E0583]: file not found for module `utilis`
  --> cilly/src/lib.rs:29:1
   |
29 | pub mod utilis;
   | ^^^^^^^^^^^^^^^
   |
   = help: to create the module `utilis`, create file "cilly/src/utilis.rs" or "cilly/src/utilis/mod.rs"
   = note: if there is a `mod utilis` elsewhere in the crate already, import it with `use crate::...` instead
```

**Example of miscompiled code**
In `rustc_codegen_clr/cilly/src/lib.rs:29` :
```
...
pub mod static_field_desc;
pub mod type_def;
pub mod utilis;
#[must_use]
...
```

**Expected behavior**
Compiling should passed without any problem following the guide.

**Info about your system (please complete the following information):**
 - OS: `Linux 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux`

**Additional context**
None

**Comment by Skgland** [comment]
Sounds more like a bug rather than a miscompilation if cilly declares a module but is missing the corresponding file with the module contents.

**Comment by FractalFir** [comment]
This should be fixed now.
